package br.com.challenge.adapter.in.rest;

import br.com.challenge.adapter.dto.CadastroMessageResponse;
import br.com.challenge.adapter.dto.CadastroRequest;
import br.com.challenge.adapter.dto.CadastroResponse;
import br.com.challenge.adapter.dto.CadastrosResponse;
import br.com.challenge.adapter.exception.InvalidUUIDException;
import br.com.challenge.application.port.in.CadastroUseCase;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.UUID;

/**
 * Resource to manage the Cadastro data on the system.
 */
@RestController
@RequestMapping("/cadastros")
public class CadastroResource {

    private static final Logger LOG = LoggerFactory.getLogger(CadastroResource.class);

    private final CadastroUseCase cadastroUseCase;

    public CadastroResource(CadastroUseCase cadastroUseCase) {
        this.cadastroUseCase = cadastroUseCase;
    }

    /**
     * API to submit a Cadastro data.
     *
     * @param cadastroRequest containing the user data.
     * @return {@link CadastroMessageResponse} with a message about the operation status.
     */
    @PostMapping(value = "/adicionar",
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<CadastroMessageResponse> createCadastro(@RequestBody @Valid final CadastroRequest cadastroRequest) {
        LOG.info("The Cadastro from client name:{}, cpf:{} will be added on the system.", cadastroRequest.nome(), cadastroRequest.cpf());
        CadastroMessageResponse response = cadastroUseCase.create(cadastroRequest);
        LOG.info("Cadastro submitted successfully from client nome:{}, cpf:{}", cadastroRequest.nome(), cadastroRequest.cpf());

        return ResponseEntity.ok(response);
    }

    /**
     * API to fetch a Cadastro data.
     *
     * @param cadastroId unique id to identify a Cadastro
     * @return {@link CadastroResponse} with the data submitted by the client and the content generated by the system.
     */
    @GetMapping(value = "/{cadastroId}")
    ResponseEntity<CadastroResponse> getByCadastroId(@PathVariable("cadastroId") final String cadastroId) {
        validateCadastroId(cadastroId);

        int status = HttpStatus.OK.value();
        LOG.info("Fetching Cadastro data cadastroId:{}.", cadastroId);
        CadastroResponse response = cadastroUseCase.getByCadastroId(cadastroId);

        if (response == null) {
            LOG.info("Cadastro not found for cadastroId:{}", cadastroId);
            status = HttpStatus.NO_CONTENT.value();
        }

        return ResponseEntity.status(status).body(response);
    }

    @GetMapping()
    ResponseEntity<CadastrosResponse> getAll() {
        LOG.info("Fetching all Cadastros");
        CadastrosResponse response = cadastroUseCase.getAll();
        LOG.info("{} Cadastros were found", response.cadastros().size());

        return ResponseEntity.ok(response);
    }

    private void validateCadastroId(final String cadastroId) {
        try {
            UUID.fromString(cadastroId);
        } catch (IllegalArgumentException e) {
            throw new InvalidUUIDException("The 'cadastroId' value is invalid");
        }
    }
}
