version: '3.8'

services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
      - CERT_PATH=/usr/local/share/ca-certificates/keystore.p12
    volumes:
      - ./data/cert/keystore.p12:/usr/local/share/ca-certificates/keystore.p12
    networks:
      - challenge-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - SERVICES=apigateway
      - DOCKER_SOCK=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost
      - LOCALSTACK_API_GATEWAY_INTEGRATION=https://host.docker.internal:8443 # For macOS/Windows
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - challenge-network
    #network_mode: host # setup to be able to call your localhost on linux OS

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./data/prometheus/certs:/etc/prometheus/certs"
      - "./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - challenge-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - challenge-network


networks:
  challenge-network:
    driver: bridge
