version: '3.8'

services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: challenge-api
    ports:
      - "8443:8443"
    environment:
      - CERT_PATH=/usr/local/share/ca-certificates/keystore.p12
    volumes:
      - ./data/certs/keystore.p12:/usr/local/share/ca-certificates/keystore.p12
    networks:
      - challenge-network

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-challenge
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - DEBUG=1
      - SERVICES=apigateway
      - DOCKER_SOCK=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost
      - LOCALSTACK_API_GATEWAY_INTEGRATION=https://challenge-api:8443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - challenge-network
    #network_mode: host # setup to be able to call your localhost on linux OS

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./data/prometheus/certs:/etc/prometheus/certs"
      - "./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - challenge-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - challenge-network

  elasticsearch:
      image: elasticsearch:8.17.0
      container_name: elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - ELASTICSEARCH_USERNAME=elastic
        - ELASTIC_PASSWORD=admin
        - ES_JAVA_OPTS=-XX:UseSVE=0
        - CLI_JAVA_OPTS=-XX:UseSVE=0
      volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data
      networks:
        - challenge-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.16.2
    container_name: filebeat-challenge
    volumes:
      - ./logs:/logs  # Mount log file to Filebeat container
      - ./data/elasticsearch/filebeat.yml:/usr/share/filebeat/filebeat.yml  # Filebeat config
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - challenge-network

networks:
  challenge-network:
    name: challenge-network
    driver: bridge
