# Spring Properties
spring:
  application:
    name: challenge
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:mydb
    hikari:
      username: sa
      password: sa
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: REPLACE
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
      mail:
        smtp:
          auth: plain
          starttls:
            enable: true

# TLS Properties
server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ${CERT_PATH:data/certs/keystore.p12}
    key-store-password: challenge
    enabled-protocols: TLSv1.2
  port: 8443

# Scheduler Properties
cron:
  notification:
    time: "1 */2 * * * *"

# Email Notification Properties
notification:
  email:
    from: REPLACE

# Observability
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Documentation
springdoc:
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
